# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orderbot', '0002_auto_20180920_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telebalancehistory',
            name='group',
        ),
        migrations.RemoveField(
            model_name='telebalancehistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='telebalancehistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teleorder',
            name='group',
        ),
        migrations.RemoveField(
            model_name='teleorder',
            name='store',
        ),
        migrations.RemoveField(
            model_name='teleorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='teleorderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='teleorderitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='telepricepolicy',
            name='store',
        ),
        migrations.RemoveField(
            model_name='teleproduct',
            name='store',
        ),
        migrations.RemoveField(
            model_name='telestore',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='teleuser',
            name='enabled_notice',
        ),
        migrations.RemoveField(
            model_name='teleuser',
            name='last_get_money_at',
        ),
        migrations.RemoveField(
            model_name='teleuser',
            name='last_notice_at',
        ),
        migrations.RemoveField(
            model_name='teleuser',
            name='time_interval_days',
        ),
        migrations.AddField(
            model_name='teleuser',
            name='credit_level',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('AA', 'AA'), ('AAA', 'AAA')], default='A', max_length=20),
        ),
        migrations.AddField(
            model_name='teleuser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TeleBalanceHistory',
        ),
        migrations.DeleteModel(
            name='TeleOrder',
        ),
        migrations.DeleteModel(
            name='TeleOrderItem',
        ),
        migrations.DeleteModel(
            name='TelePricePolicy',
        ),
        migrations.DeleteModel(
            name='TeleProduct',
        ),
        migrations.DeleteModel(
            name='TeleStore',
        ),
    ]
