# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbot', '0004_teleuser_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleuser',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
