# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbot', '0005_auto_20180925_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_currency', models.CharField(choices=[('CNY', 'CNY'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=30)),
                ('buy_currency', models.CharField(choices=[('CNY', 'CNY'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
