# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_currency', models.CharField(choices=[('CNY', 'CNY'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=30)),
                ('buy_currency', models.CharField(choices=[('CNY', 'CNY'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=30)),
                ('max_amount', models.PositiveSmallIntegerField(default=0)),
                ('min_amount', models.PositiveSmallIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeleBalanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diff', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('create_orderitem', 'create order item'), ('delete_orderitem', 'delete order item'), ('cancel_order', 'cancel order'), ('discard_order', 'discard order'), ('recharge', 'recharge'), ('transfer', 'transfer'), ('fee', 'fee')], max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=100)),
                ('created_by', models.CharField(choices=[('Admin', 'Administrator'), ('Driver', 'Driver'), ('System', 'System')], max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('chat_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=100, unique=True)),
                ('purpose', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Supper', 'Supper'), ('others', 'others')], default='Breakfast', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeleMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subscribed', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='exchange.TeleGroup')),
            ],
        ),
        migrations.CreateModel(
            name='TeleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('delivery_at', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'epen'), ('closed', 'closed'), ('shipped', 'shipped'), ('received', 'received'), ('invalid', 'invalid')], default='open', max_length=10)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchange.TeleGroup')),
            ],
        ),
        migrations.CreateModel(
            name='TeleOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('is_union_price', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exchange.TeleOrder')),
            ],
        ),
        migrations.CreateModel(
            name='TelePricePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unioncode', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TeleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_union_price', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('0', 'vegetables'), ('1', 'meat'), ('2', 'littemeat'), ('3', 'fruit'), ('4', 'rice'), ('5', 'soup')], default='0', max_length=10)),
                ('role', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Supper', 'Supper'), ('All', 'All')], default='Breakfast', max_length=20)),
                ('enabled_day', models.CharField(choices=[('0', 'Anyday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TeleStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('wechat_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('level', models.CharField(blank=True, choices=[('Five', 'Five Stars'), ('Four', 'Four Stars'), ('Three', 'Three Stars'), ('Two', 'Two Stars'), ('One', 'One Star')], default='Three', max_length=20)),
                ('supply_bre', models.BooleanField(default=False)),
                ('supply_lun', models.BooleanField(default=False)),
                ('supply_sup', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('role', models.CharField(blank=True, choices=[('Admin', 'Administrator'), ('GroupAdmin', 'Group Administrator'), ('Driver', 'Driver'), ('Merchant', 'Merchant'), ('User', 'Common User')], default='User', max_length=20)),
                ('enabled_notice', models.BooleanField(default=False)),
                ('last_notice_at', models.DateTimeField(blank=True, null=True)),
                ('last_get_money_at', models.DateTimeField(blank=True, null=True)),
                ('time_interval_days', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='telestore',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.TeleUser'),
        ),
        migrations.AddField(
            model_name='teleproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='exchange.TeleStore'),
        ),
        migrations.AddField(
            model_name='telepricepolicy',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_policies', to='exchange.TeleStore'),
        ),
        migrations.AddField(
            model_name='teleorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.TeleProduct'),
        ),
        migrations.AddField(
            model_name='teleorderitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='exchange.TeleUser'),
        ),
        migrations.AddField(
            model_name='teleorder',
            name='store',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='exchange.TeleStore'),
        ),
        migrations.AddField(
            model_name='telemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='exchange.TeleUser'),
        ),
        migrations.AddField(
            model_name='teleimage',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.TeleUser'),
        ),
        migrations.AddField(
            model_name='telegroup',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drived_group', to='exchange.TeleUser'),
        ),
        migrations.AddField(
            model_name='telegroup',
            name='images',
            field=models.ManyToManyField(to='exchange.TeleImage'),
        ),
        migrations.AddField(
            model_name='telegroup',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_groups', to='exchange.TeleUser'),
        ),
        migrations.AddField(
            model_name='telegroup',
            name='members',
            field=models.ManyToManyField(through='exchange.TeleMembership', to='exchange.TeleUser'),
        ),
        migrations.AddField(
            model_name='telebalancehistory',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_history', to='exchange.TeleGroup'),
        ),
        migrations.AddField(
            model_name='telebalancehistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balances', to='exchange.TeleOrder'),
        ),
        migrations.AddField(
            model_name='telebalancehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_history', to='exchange.TeleUser'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='exchange.TeleUser'),
        ),
    ]
