# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='max_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='min_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
