# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20180923_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleuser',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
