# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_auto_20180928_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='buy_currency',
            field=models.CharField(choices=[('CNY', 'CNY'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=30),
        ),
        migrations.AlterField(
            model_name='bid',
            name='sell_currency',
            field=models.CharField(choices=[('CNY', 'CNY'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=30),
        ),
    ]
