# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_auto_20181002_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='buy_currency',
            field=models.CharField(choices=[('CNY', 'CNY'), ('PHP', 'PHP'), ('USD', 'USD'), ('TWD', 'TWD')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rate',
            name='sell_currency',
            field=models.CharField(choices=[('CNY', 'CNY'), ('PHP', 'PHP'), ('USD', 'USD'), ('TWD', 'TWD')], max_length=30),
        ),
    ]
