# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_auto_20181003_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleuser',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
