# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_teleuser_is_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teleuser',
            name='is_connected',
        ),
        migrations.AddField(
            model_name='teleuser',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
