# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_auto_20181003_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teleuser',
            name='short_name',
        ),
    ]
