# Generated by Django 2.1 on 2019-03-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_remove_teleuser_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='buy_currency',
            field=models.CharField(choices=[('CNY', 'CNY'), ('PHP', 'PHP'), ('USD', 'USD'), ('TWD', 'TWD'), ('HKD', 'HKD')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rate',
            name='sell_currency',
            field=models.CharField(choices=[('CNY', 'CNY'), ('PHP', 'PHP'), ('USD', 'USD'), ('TWD', 'TWD'), ('HKD', 'HKD')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teleuser',
            name='chat_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teleuser',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
