# Generated by Django 2.1 on 2019-04-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0013_auto_20190307_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
